# Docs: <https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/customizing-dependency-updates>

version: 2
updates:
  - package-ecosystem: github-actions
    cooldown:
      default-days: 7
    directory: /
    schedule:
      interval: weekly
      day: 'tuesday'
      time: '01:00'
      timezone: 'Asia/Kolkata'
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: docker
    cooldown:
      default-days: 7
    directory: /
    schedule:
      interval: weekly
      day: 'tuesday'
      time: '01:00'
      timezone: 'Asia/Kolkata'
    open-pull-requests-limit: 5
    groups:
      docker:
        patterns:
          - '*'
