
[packages.sable]
versioned_files = ["package.json", "package-lock.json"]
changelog = "CHANGELOG.md"
extra_changelog_sections = [
    { name = "Documentation", types = ["docs"] },
    { name = "Notes", types = ["note"] },
    { types = ["patch"], name = "Updates" },
]
# assets = "marker for GitHub bot" // TODO: add this later once we have assets

[changes]
ignore_conventional_commits = true

[[workflows]]
name = "release"
help_text = "Prepare and create a new release (update changelog, bump version, create release)"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = 'git commit -m "chore: prepare release $version"'

[[workflows.steps]]
type = "Command"
command = "git push"

[[workflows.steps]]
type = "Release"

[[workflows]]
name = "document-change"
help_text = "Create a new change file to be included in the next release"

[[workflows.steps]]
type = "CreateChangeFile"

[github]
owner = "7w1"
repo = "sable"

[bot.releases]
enabled = true
pull_request.title = "$version changelog"

[bot.checks]
skip_labels = ["internal"]

[release_notes]
change_templates = [
    "* $summary - $commit_author_name ($commit_hash)",
    "* $summary",
]