[packages.sable]
versioned_files = ["package.json", "package-lock.json"]
changelog = "CHANGELOG.md"
extra_changelog_sections = [
    { name = "Documentation", types = ["docs"] },
    { name = "Notes", types = ["note"] },
]
# assets = "marker for GitHub bot" // TODO: add this later once we have assets

[changes]
ignore_conventional_commits = true

[[workflows]]
name = "prepare-release"
help_text = "Bump version and update changelog for the next release (used by CI)"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows]]
name = "release"
help_text = "Create a GitHub release for the sable package (used by CI after PR merge)"

[[workflows.steps]]
type = "Release"

[[workflows]]
name = "document-change"
help_text = "Create a new change file to be included in the next release"

[[workflows.steps]]
type = "CreateChangeFile"

[github]
owner = "SableClient"
repo = "Sable"

[release_notes]
change_templates = [
    "* $summary",
]
